In [2]:
import numpy as np
from gates import (Z, X, Y, H, CNOT, CZ, P, T, S, applyGate, kron)

# basics

In [3]:
s0 = np.array([1,0])
s1 = np.array([0,1])
sp = (1/np.sqrt(2))*np.array([1,1])
sm = (1/np.sqrt(2))*np.array([1,-1])
sT = (1/np.sqrt(2)) * (s0 + np.exp(1j*np.pi/4)*s1)

(
    applyGate(H, s0) == sp, 
    applyGate(H, s1) == sm, 
    applyGate(H, sp) == s0, 
    applyGate(H, sm) == s1,
    
    applyGate(X, s0) == s1,
    applyGate(X, s1) == s0,
    applyGate(X, sm) == -sm,
    applyGate(X, sp) == sp,
    
    )

(array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]),
 array([ True,  True]))

# Apply X, Y, Z, H, and T to $\ket{0}$, $\ket{1}$, $\ket{+}$, $\ket{T} = (\ket{0}+e^{i\pi/4}\ket{1})/\sqrt{2}$

In [4]:
results = (
    applyGate(X, s0) == s1,
    applyGate(X, s1) == s0,
    applyGate(X, sp) == sp,
    applyGate(X, sm) == -sm,
    applyGate(X, sT),
    "------------------",
    applyGate(Y, s0) == 1j*s1,
    applyGate(Y, s1) == -1j*s0,
    applyGate(Y, sp) == -1j*sm,
    applyGate(Y, sm) == 1j*sp,
    applyGate(Y, sT),
    "------------------",
    applyGate(Z, s0) == s0,
    applyGate(Z, s1) == -s1,
    applyGate(Z, sp) == sm,
    applyGate(Z, sm) == sp,
    applyGate(Z, sT),
    "------------------",
    applyGate(H, s0) == sp,
    applyGate(H, s1) == sm,
    applyGate(H, sp) == s0,
    applyGate(H, sm) == s1,
    applyGate(H, sT),
    
)

with np.printoptions(precision=3, suppress=True):
    for res in results:
        print(res)
        # res

[ True  True]
[ True  True]
[ True  True]
[ True  True]
[0.5  +0.5j 0.707+0.j ]
------------------
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[0.5-0.5j   0. +0.707j]
------------------
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ 0.707+0.j  -0.5  -0.5j]
------------------
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[0.854+0.354j 0.146-0.354j]


# 2qubit states and CNOT, CZ

In [6]:
s00 = kron(s0, s0)
s01 = kron(s0, s1)
s10 = kron(s1, s0)
s11 = kron(s1, s1)
sp0 = kron(sp, s0)
spp = kron(sp, sp)

results = (
    "CNOT",
    applyGate(CNOT, s00) == s00,
    applyGate(CNOT, s01) == s01,
    applyGate(CNOT, s11) == s10,
    applyGate(CNOT, sp0) == (s00 + s11)/np.sqrt(2),
    applyGate(CNOT, spp) == spp,
    "------------------",
    "CZ",
    applyGate(CZ, s00) ==  s00,
    applyGate(CZ, s01) ==  s01,
    applyGate(CZ, s10) == s10,
    applyGate(CZ, s11) == -s11,
    applyGate(CZ, sp0) == sp0,
    np.isclose(applyGate(CZ, spp), (1/2) * (s00 + s01 + s10 - s11))
)

for res in results:
    print(res)

CNOT
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
------------------
CZ
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]


# Implement quantum teleportation register

Given the system  

![Quantum teleportation circuit](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Quantum_teleportation_circuit.svg/1920px-Quantum_teleportation_circuit.svg.png)

We want to determine the operations needed for the system.





$$
    (M\otimes CNOT)(I\otimes M\otimes I)(H\otimes M\otimes I)(CNOT\otimes I)\ket{\psi}_A\ket{\phi}_A^+\ket{\phi}_B^+
$$

In [163]:
I = np.eye(2)

s000 = kron(s0, s0, s0); print(f"{s000 = }")
s001 = kron(s0, s0, s1); print(f"{s001 = }")
s010 = kron(s0, s1, s0); print(f"{s010 = }")
s011 = kron(s0, s1, s1); print(f"{s011 = }")
s100 = kron(s1, s0, s0); print(f"{s100 = }")
s101 = kron(s1, s0, s1); print(f"{s101 = }")
s110 = kron(s1, s1, s0); print(f"{s110 = }")
s111 = kron(s1, s1, s1); print(f"{s111 = }")
print(kron(CNOT, I))
np.all(kron(CNOT, I) @ s110 == s100)

s000 = array([1, 0, 0, 0, 0, 0, 0, 0])
s001 = array([0, 1, 0, 0, 0, 0, 0, 0])
s010 = array([0, 0, 1, 0, 0, 0, 0, 0])
s011 = array([0, 0, 0, 1, 0, 0, 0, 0])
s100 = array([0, 0, 0, 0, 1, 0, 0, 0])
s101 = array([0, 0, 0, 0, 0, 1, 0, 0])
s110 = array([0, 0, 0, 0, 0, 0, 1, 0])
s111 = array([0, 0, 0, 0, 0, 0, 0, 1])
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


np.True_

In [ ]:
inputState = s100
inputState

def Measure(state, basis="Z"):
    
    mes = Z @ state
    return 
    



part1 = (kron(CNOT, I)) @ inputState; print(part1 == s110)
part2 = (kron(H, I, I)) @ part1
Measure(part2), part2

[ True  True  True  True  True  True  True  True]


(array([0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0. ]),
 array([ 0.        ,  0.        ,  0.70710678,  0.        ,  0.        ,
         0.        , -0.70710678,  0.        ]))